### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ajcarney**

### CODE REVIEW

**Comment by dtcarney741** [comment]
When loading the attached DSM, there are many warnings in the console that look like this:
Aug 28, 2022 8:08:06 AM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Color (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Color is in unnamed module of loader 'app')' while converting value for '-fx-background-color' from rule '*.text-input' in stylesheet jar:file:/home/dtcarney/.m2/repository/org/openjfx/javafx-controls/17.0.2/javafx-controls-17.0.2-linux.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
[input_Test_basic_set_connection_functionality.zip](https://github.com/ajcarney/DSMEditor/files/9439707/input_Test_basic_set_connection_functionality.zip)

**Comment by dtcarney741** [comment]
When changing a row/col from one group to another if they have different text colors for the group setting, the X's that are no longer in the old groups colored boxes remain the text color of the old group. They should switch color back to black since they are no longer in a colored group box.
You can easily reproduce this in the attached DSM by switching D to G1 and then back to G2. If you zoom in and out the problem is fixed
[defect_group_text_color.zip](https://github.com/ajcarney/DSMEditor/files/9439724/defect_group_text_color.zip)
.

**Comment by ajcarney** [comment]
For the first one, those warnings are something to do with how the javafx library and the run configuration. They don't really affect anything so I've been ignoring them when they happen. When executing with a maven run configuration they do not appear. 

I fixed the second bug and will make another qa pull request for you

**Comment by dtcarney741** [comment]
When performing a save as, the file name of the tab does not change. The file does get saved to the new name.

**Comment by ajcarney** [comment]
Maybe I'm unclear on the save as functionality, but the expected behavior is that the file is saved to a new location and both the original and new files both exist and would be the same. However, the new file is not opened automatically and it only shows the old saved file. So, should it (1) open the new saved file for the expected behavior? (2) Should the old file be closed afterward? As of right now, this is expected behavior

**Comment by dtcarney741** [comment]
I think save-as should work like it does in standard office programs. When you save-as, the file is saved to the new name, no update is made to the existing file, and the active file in the tool is the new name. Any future saves that occur are to the new name.

**Comment by dtcarney741** [comment]
I found an interesting bug. If you sort in a zoomed view of a multi-domain while zoomed to same domain on row and col access, only the row is sorted. When you apply this back to the main multi-domain DSM the same thing occurs. If you subsequently sort that row again, the col does not move, though the row does. I did confirm that sorting of other row/cols on the multi-domain view works as normal.
This sorting while in a zoom view seems to have gotten the tool out of sync. Also, when saving this file, it cannot be reloaded. I am attaching it here for you
[multi_domain_sorting_defect.zip](https://github.com/ajcarney/DSMEditor/files/9492210/multi_domain_sorting_defect.zip)

Also attaching a screen capture showing the sorting defect.

test_fail_zoom_view

**Comment by dtcarney741** [comment]
The same thing happens if you add a new row col in a multi-domain matrix and then try to sort it on the main view. The column won't sort. So I think the bug is more with the adding row/cols in a zoom view than with the sorting them in the zoom view.
I did confirm if you add new row/col items on the main view tab that they sort correctly.

**Comment by dtcarney741** [comment]
Here is the test report. All of the defects that I found have been posted as comments. You can find more details about how to reproduce in the report or by logging in to Qase and running the tests yourself.

I still intend to create some test cases for asymmetric DSMs. I'll also send you a completed version of the satellite multi-domain DSM for you to include as an example on Github. I think we're getting very close to a release. It looks great and works awesome over all. I have some minor enhancement requests, but I'm going to hold off on those for this release.

**Comment by dtcarney741** [comment]
All right, I can reliably reproduce with the attached DSM and the following minimum steps (I started with the full steps in the Qase test case and backed them out and executed them in different orders until I identified that this is the minimum sequence of things to do to reproduce:
1) Open the DSM
2) Zoom to default-default
3) Add a new row/col called Z
4) Apply changes back to main DSM
5) Close the breakout window
6) Sort Z in the main DSM window (the row position will change but the column will not)

The steps omitted that don't seem to have any relevance from the original Qase test case are:
* Appending connections to Z in the zoom window
* Changing the group in the zoom window
* Sorting in the zoom window
Also, with this DSM, I confirmed that I can add Z into the main window, append connections to it, change its group, and sort it without the bug happening. It's only when adding it in the zoom.

[input_MDM_Test_Multi-domain_clustering_analysis.zip](https://github.com/ajcarney/DSMEditor/files/9540816/input_MDM_Test_Multi-domain_clustering_analysis.zip)

**Comment by ajcarney** [comment]
I downloaded your DSM file and followed the steps to try to reproduce it, but was still not able to. I also tried it with my own test DSM and still could not reproduce it. I even stashed my changes and switched to this branch and could not reproduce it. I have no idea why you are getting the behaviour you are seeing. Could you try re-cloning the repository with the current branch and see if that fixes things for you?

**Comment by dtcarney741** [comment]
I cloned a new repo on the Linux machine. I cannot reproduce with a build and run from the new repo. I can still reliably reproduce in the old clone on this Linux machine.

**Comment by dtcarney741** [comment]
I get a bunch of errors in the console like this when I open the attached non-symmetric DSM:
Sep 18, 2022 12:06:57 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Color (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Color is in unnamed module of loader 'app')' while converting value for '-fx-background-color' from rule '*.menu-bar' in stylesheet jar:file:/home/dtcarney/.m2/repository/org/openjfx/javafx-controls/17.0.2/javafx-controls-17.0.2-linux.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss


Also, I noticed an interesting behavior. When you try to open a file with the same name as a modified version that is already opened, it doesn't actually load, but also gives no indication that it didn't load.

[input_nonsymmetric_Test_Propagation_analysis.zip](https://github.com/ajcarney/DSMEditor/files/9594722/input_nonsymmetric_Test_Propagation_analysis.zip)

**Comment by dtcarney741** [comment]
Also, for the matrix attached in the previous comment, try the transpose function. It gives really funky results.

**Comment by ajcarney** [comment]
1. I am going to consider the zooming issue resolved at this point as neither one of us can reproduce it with a current build
2. Those warnings are not important. I know what the issue is but I am not going to fix it for a while as it is more work than it is worth at this point. From now on you can ignore any javafx warnings like ClassCastException
3. This might be correct behavior. When you try to open a file that is already opened it just focuses the tab with that file. It is comparing off of absolute path so I am not sure if this is actually an issue. I tried reproducing with same name file, but different path and could not get your behavior
4. fixed

**Pull request merged**
